// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TinderAppAPI.Migrations
{
    [DbContext(typeof(TinderDBContext))]
    [Migration("20241128103602_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.User.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reading 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reading 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reading 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reading 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Reading 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Reading 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Reading 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Reading 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Reading 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Reading 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Traveling 1"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Traveling 2"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Traveling 3"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Traveling 4"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Traveling 5"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Traveling 6"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Traveling 7"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Traveling 8"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Traveling 9"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Traveling 10"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Cooking 1"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Cooking 2"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cooking 3"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Cooking 4"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Cooking 5"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Cooking 6"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Cooking 7"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cooking 8"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cooking 9"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cooking 10"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Photography 1"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Photography 2"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Photography 3"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Photography 4"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Photography 5"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Photography 6"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Photography 7"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Photography 8"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Photography 9"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Photography 10"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Music 1"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Music 2"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Music 3"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Music 4"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Music 5"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Music 6"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Music 7"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Music 8"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Music 9"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Music 10"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Movies 1"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Movies 2"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Movies 3"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Movies 4"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Movies 5"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Movies 6"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Movies 7"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Movies 8"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Movies 9"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Movies 10"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Hiking 1"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Hiking 2"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Hiking 3"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Hiking 4"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Hiking 5"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Hiking 6"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Hiking 7"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Hiking 8"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Hiking 9"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Hiking 10"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Fitness 1"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Fitness 2"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Fitness 3"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Fitness 4"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Fitness 5"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Fitness 6"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Fitness 7"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Fitness 8"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Fitness 9"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Fitness 10"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Gaming 1"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Gaming 2"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Gaming 3"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Gaming 4"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Gaming 5"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Gaming 6"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Gaming 7"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Gaming 8"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Gaming 9"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Gaming 10"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Dancing 1"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Dancing 2"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Dancing 3"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Dancing 4"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Dancing 5"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Dancing 6"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Dancing 7"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Dancing 8"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Dancing 9"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Dancing 10"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Art 1"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Art 2"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Art 3"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Art 4"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Art 5"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Art 6"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Art 7"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Art 8"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Art 9"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Art 10"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Coding 1"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Coding 2"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Coding 3"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Coding 4"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Coding 5"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Coding 6"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Coding 7"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Coding 8"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Coding 9"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Coding 10"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Blogging 1"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Blogging 2"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Blogging 3"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Blogging 4"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Blogging 5"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Blogging 6"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Blogging 7"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Blogging 8"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Blogging 9"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Blogging 10"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Yoga 1"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Yoga 2"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Yoga 3"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Yoga 4"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Yoga 5"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Yoga 6"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Yoga 7"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Yoga 8"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Yoga 9"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Yoga 10"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Gardening 1"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Gardening 2"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Gardening 3"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Gardening 4"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Gardening 5"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Gardening 6"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Gardening 7"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Gardening 8"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Gardening 9"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Gardening 10"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Cycling 1"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Cycling 2"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Cycling 3"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Cycling 4"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Cycling 5"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Cycling 6"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Cycling 7"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Cycling 8"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Cycling 9"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Cycling 10"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Fishing 1"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Fishing 2"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Fishing 3"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Fishing 4"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Fishing 5"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Fishing 6"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Fishing 7"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Fishing 8"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Fishing 9"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Fishing 10"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Sports 1"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Sports 2"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Sports 3"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Sports 4"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Sports 5"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Sports 6"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Sports 7"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Sports 8"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Sports 9"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Sports 10"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Meditation 1"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Meditation 2"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Meditation 3"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Meditation 4"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Meditation 5"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Meditation 6"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Meditation 7"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Meditation 8"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Meditation 9"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Meditation 10"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Learning Languages 1"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Learning Languages 2"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Learning Languages 3"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Learning Languages 4"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Learning Languages 5"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Learning Languages 6"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Learning Languages 7"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Learning Languages 8"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Learning Languages 9"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Learning Languages 10"
                        });
                });

            modelBuilder.Entity("Data.Entities.User.ProfilePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProfilePhotos");
                });

            modelBuilder.Entity("Data.Entities.User.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("InterestedIn")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LookingFor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexualOrientation")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.User.Interest", b =>
                {
                    b.HasOne("Data.Entities.User.User", null)
                        .WithMany("Interests")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.Entities.User.ProfilePhoto", b =>
                {
                    b.HasOne("Data.Entities.User.User", "User")
                        .WithMany("ProfilePhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Entities.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.User.User", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("ProfilePhotos");
                });
#pragma warning restore 612, 618
        }
    }
}
